# Generated by Django 3.0 on 2019-04-03 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='salting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64)),
                ('password', models.CharField(max_length=64)),
                ('salt', models.CharField(max_length=64)),
                ('salt_pos', models.CharField(max_length=64)),
            ],
        ),
    ]
