# Generated by Django 3.0 on 2019-04-03 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salting',
            name='old',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
