# Generated by Django 3.0 on 2019-04-03 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salting', '0002_salting_old'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salting',
            name='old',
        ),
    ]
